version: '3.9'
services:
  backend:
    build: ./tiffinbox-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tiffinbox-backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./tiffinbox-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: tiffinbox
      POSTGRES_PASSWORD: tiffinpass
      POSTGRES_DB: tiffindb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
